<?php

namespace Modules\BusinessManagement\Http\Controllers\Web\Admin\Configuration;

use App\Http\Controllers\BaseController;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\View\View;
use Modules\BusinessManagement\Http\Requests\SmsSettingSetupStoreOrUpdateRequest;
use Modules\BusinessManagement\Service\Interfaces\SettingServiceInterface;
use Modules\Gateways\Traits\Processor;
use Modules\Gateways\Traits\SmsGateway;
use Modules\Gateways\Traits\SmsGatewayForMessage;

class SMSConfigController extends BaseController
{
    use Processor;

    protected $settingService;
    public function __construct(SettingServiceInterface $settingService)
    {
        parent::__construct($settingService);
        $this->settingService = $settingService;
    }

    public function index(?Request $request, string $type = null): View|Collection|LengthAwarePaginator|null|callable|RedirectResponse
    {
        return parent::index($request, $type); // TODO: Change the autogenerated stub
    }

    public function smsConfigGet(): Application|Factory|\Illuminate\Contracts\View\View|\Illuminate\Foundation\Application
    {
        $dataValues = $this->settingService->getBy(criteria: ['settings_type' => SMS_CONFIG]);
        return view('businessmanagement::admin.configuration.sms-gateway', compact('dataValues'));
    }

    /**
     * Display a listing of the resource.
     * @param Request $request
     * @return RedirectResponse
     */
    public function smsConfigSet(SmsSettingSetupStoreOrUpdateRequest $request): RedirectResponse
    {
        $this->settingService->storeOrUpdateSMSSetting($request->validated());
        Toastr::success(DEFAULT_UPDATE_200['message']);
        return back();
    }

    public function testSms(Request $request): JsonResponse
    {
        $request->validate([
            'phone' => 'required|string',
            'gateway' => 'required|string',
        ]);

        $gateway = $request->input('gateway');
        $phone = $request->input('phone');
        $message = $request->input('message', 'Test SMS from Xerin Express. Your OTP is 1234');

        try {
            $config = \Modules\Gateways\Traits\SmsGateway::get_settings($gateway);

            if (!isset($config) || $config['status'] != 1) {
                return response()->json([
                    'success' => false,
                    'message' => ucfirst(str_replace('_', ' ', $gateway)) . ' gateway is not active. Please activate it first.',
                ]);
            }

            $otp = '1234';
            $result = 'not_found';

            if (method_exists(SmsGateway::class, $gateway)) {
                $result = SmsGateway::{$gateway}($phone, $otp);
            } elseif (method_exists(SmsGatewayForMessage::class, $gateway)) {
                $result = SmsGatewayForMessage::{$gateway}($phone, $message, $config);
            }

            if ($result === 'success') {
                return response()->json([
                    'success' => true,
                    'message' => 'SMS sent successfully to ' . $phone . ' via ' . ucfirst(str_replace('_', ' ', $gateway)),
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'SMS sending failed via ' . ucfirst(str_replace('_', ' ', $gateway)) . '. Check SMS logs for details.',
                ]);
            }
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Error: ' . $e->getMessage(),
            ]);
        }
    }
}
